server:
  port : 8080

spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.0.28:4406/happyAndDaily?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    show-sql: true
  devtools:
    # Auto Restart
    restart:
      enabled: true
      #additional-paths: static/**
    # Live Reload
    livereload:
      enabled: true
  thymeleaf:
    cache: false
#    prefix: classpath:templates/
#    suffix: .html
  mvc:
    view:
      suffix: .html