server:
  port : 8080

spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.0.28:4406/happyAndDaily?useUnicode=true&characterEncoding=utf-8
    username: happyAndDaily
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  thymeleaf:
    cache: false
  mvc:
    view:
      suffix: .html