server:
  port : 8081

spring:
  config:
    activate:
      on-profile: dev
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        use-new-id-generator-mappings: true #ID 자동증가
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          batch_size: 100
    hibernate:
      ddl-auto: create
    datasource:
      driverClassName: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://192.168.0.28:4406/happyAndDaily?useUnicode=true&characterEncoding=utf-8
      username: happyAndDaily
      password: root
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          format_sql: true
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  thymeleaf:
    cache: false
  mvc:
    view:
      suffix: .html

logging:
  level:
    root: INFO