server:
  port : 8080

spring:
  config:
    activate:
      on-profile: dev
  data:
    rest:
      base-path: /api
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        use-new-id-generator-mappings: true #ID 자동증가
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          batch_size: 100
    hibernate:
      ddl-auto: create
    datasource:
      driverClassName: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://192.168.0.28:4406/happyAndDaily?useUnicode=true&characterEncoding=utf-8
      username: happyAndDaily
      password: root
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          format_sql: true
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  thymeleaf:
    cache: false
  mvc:
    view:
      suffix: .html

logging:
  level:
    root: INFO
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: b774a11d0f7cc39ac37d9966a5cd2061
            scope:
              - account_email
              - profile_nickname
              - profile_image
              - gender
              - birthday
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: kakao
            client-authentication-method: POST
          naver:
            client-id: MxPM4eOxK732J3CkgZdF
            client-secret: stsSFHxiSI
            scope:
              - name
              - email
              - nickname
              - profile_image
              - birthday
              - gender
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            client-name: naver
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response