server:
  port : 8080

spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        use-new-id-generator-mappings: true #ID 자동증가
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          batch_size: 100
    hibernate:
      ddl-auto: create
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true
  thymeleaf:
    cache: false
  mvc:
    view:
      suffix: .html
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: b774a11d0f7cc39ac37d9966a5cd2061
            scope:
              - account_email
              - profile_nickname
              - profile_image
              - gender
              - birthday
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: kakao
            client-authentication-method: POST
          naver:
            client-id: MxPM4eOxK732J3CkgZdF
            client-secret: stsSFHxiSI
            scope:
              - name
              - email
              - nickname
              - profile_image
              - birthday
              - gender
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            client-name: naver
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
kakao:
  js-key: 5f658edc38edb2f9ede95d1dbfd24d3a