server:
  port : 8080

spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        use-new-id-generator-mappings: true #ID 자동증가
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          batch_size: 100
    hibernate:
      ddl-auto: create
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  thymeleaf:
    cache: false
  mvc:
    view:
      suffix: .html